# Generated by Django 2.0.4 on 2018-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bichos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=40, verbose_name='Mote')),
                ('skills', models.IntegerField(verbose_name='Habilidad')),
                ('force', models.IntegerField(verbose_name='Fuerza')),
                ('resistance', models.IntegerField(verbose_name='Resistencia')),
            ],
            options={
                'verbose_name': 'Jugadores',
            },
        ),
    ]
