# Generated by Django 2.0.4 on 2018-04-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20180423_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Escuelas'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Estudiantes'},
        ),
    ]
